### ISSUE TITLE
Verify if page is on Tor Network

### ISSUE THREAD

**Issue by andrealmeid** [andrealmeid/cybercrime-scrapper#3]
It's also important to check if has a Tor2Web interface (such http://onion.link/). Some examples (check http://cybercrime-tracker.net/index.php?search=onion) don't have it, and will need to be scanned using proxy.

**Comment by mdanilor** [comment]
All examples will be crawled through Tor2Web. Links which do not have a .onion.to or .onion.link ending must be rewritten. Portscans should preferably be done manually.

**Comment by mdanilor** [comment]
Solved on #9.
